[tool.uv.workspace]
members = ["cli", "common", "rag"]

[tool.uv.sources]
cli = { workspace = true }
common = { workspace = true }
rag = { workspace = true }

[project]
name = "localllm"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "cli",
    "common",
    "rag",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
