[tool.uv.workspace]
members = ["cli", "common", "mcp", "rag", "server"]

[tool.uv.sources]
cli = { workspace = true }
common = { workspace = true }
mcp-server = { workspace = true }
rag = { workspace = true }
server = { workspace = true }

[project]
name = "localllm"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "cli",
    "common",
    "mcp-server",
    "rag",
    "server",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
testpaths = ["cli/tests", "mcp/tests", "server/tests", "rag/tests"]
