[project]
name = "rag"
version = "0.1.0"
description = "RAG pipeline for localLLM application"
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "langchain",
    "langchain-community",
    "langchain-text-splitters",
    "ollama",
    "pydantic",
    "pydantic-settings",
    "psycopg2-binary",
    "langchain-ollama",
    "langchain-postgres",
    "sqlalchemy",
    "beautifulsoup4",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["rag"]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
